export var mailType = {
    MAIL_CREATE: 200,
    MAIL_RESETPASSWORD: 401,
    MAIL_FORGOTPASSWORD: 404,
    MAIL_SUCCESS: 500,
    MAIL_FORGOTPASSWORD_SUCCESS: 405,

    // env
    JWT_SECRET_KEY3: 'easdfasdfasf',
    JWT_FORGOTPASSWORD_EXPIRE_TIME: '3m'
}